# IN TERMINAL TYPE THE FOLLOWING:  Rscript source_files.R

source("Australia/poll.R")
source("Canada/poll.R")
source("Croatia/poll.R")
source("Dutch/poll.R")
source("German/Federal/poll.R")
source("German/State/Thuringia/poll.R")
# source("Greece/poll.R")
source("Greece/poll2.R")
source("Icelandic/poll.R")
source("Irish/poll.R")
source("Lithuanian/poll.R")
# source("Montenegro/poll.R")
source("NewZealand/poll.R")
source("Norwegian/poll.R")
source("Polish/Seats/poll.R")
source("Polish/Seats/poll2.R")
source("Polish/Votes/poll.R")
source("Slovak/poll.R")
source("Swedish/poll.R")
source("Turkish/Campaign/poll.R")
source("UK/general_polling/poll.R")
source("UK/Subnational/Scotland/poll.R")
source("UK/Subnational/Scotland/poll2.R")
source("UK/Subnational/Wales/poll.R")
source("UK/Subnational/Wales/poll_Senedd.R")
