# IN TERMINAL TYPE THE FOLLOWING:  Rscript source_files.R

source("Austrian/poll.R")
source("Austrian/poll_coalition.R")
source("Australia/poll.R")
source("Belgian/poll.R")
source("Canada/Federal/poll.R")
source("Canada/Provincial/British Columbia/poll.R")
source("Canada/Provincial/Quebec/poll.R")
source("Croatia/poll.R")
source("Denmark/poll.R")
source("Dutch/poll_new.R")
source("Dutch/poll_long.R")
source("Finnish/poll2.R")
source("German/Federal/poll.R")
source("German/Federal/poll2.R")
source("German/Federal/poll3.R")
# source("German/Federal/poll_BSW.R")
source("German/State/Thuringia/poll.R")
source("Icelandic/poll.R")
source("Irish/poll.R")
source("Italy/poll.R")
source("Japan/poll.R")
source("Japan/poll2.R")
source("Lithuanian/poll.R")
source("Norwegian/poll.R")
source("South Africa/poll.R")
source("Spain/poll_new.R")
source("Spain/poll2_new.R")
source("Spain/poll_long.R")
source("Swedish/poll.R")
source("Swedish/poll_long.R")
source("Taiwan/poll.R")
source("UK/general_polling/poll.R")
source("UK/Subnational/Scotland/poll.R")
source("UK/Subnational/Scotland/poll2.R")
source("UK/Subnational/Wales/poll.R")
source("UK/Subnational/Wales/poll_Senedd.R")
